# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d256afadc281d6d43a5208690686ccd55f7d6bb725068638aabd458ab54d3ee08e83bb423bbb6edfc0e3befdb65af2bf859c19d114a2ac959d3663e2106eba30

test:
  secret_key_base: 5085e5e106c4e17b5c6bf4cdc5caa00e09cf0c4eae4775cbbba5c1bba4178d604f15c59653e13b1233b0cee11251ee0726cad0227abe19cabb2cdacbbba0bb3e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
